### ISSUE TITLE
run time error in .NET project

### ISSUE THREAD

**Issue by kisu2511** [HeinzBenjamin/FlexCLI#5]
Hello. @HeinzBenjamin 

I want to use flex in my own .net project.
So, I followed your option2 in instruction page.
build sequence is fine.
however, at runtime, it continuously shows exception about "System.IO.FileNotFoundException".
"FlexCLI.dll" or dependent file or assembly is not loaded.

I did all thing that i can do.
update graphic driver, install windows SDK, and install grasshopper and rhino5.
But still the error message is shown at runtime.

did i miss something?
or how can i debug the code in runtime.
Thank you in advance.

**Comment by HeinzBenjamin** [comment]
Hello Kisu,

can you please retry? I just pushed a new version to Github.
Always make sure to unblock all components... (Right click on the .dlls --> Properties --> Tick "Unblock")

Best
Ben

**Comment by kisu2511** [comment]
@HeinzBenjamin 

Sorry for bothering you.

I tested the new version of FlexCLI as your comment.
However, it still failed at runtime. Same error message.

for testing your library, I just made test .net console application (only use the main function, in VS2017),
and using flex library as follows:

Flex f = new Flex();

and it still popped up runtime error message. (i just use your library files in bin/debug folder).

"System.IO.FileNotFoundException".
"FlexCLI.dll" or dependent file or assembly is not loaded.

how can I solve this problem?
Thank you in advance.

**Comment by HeinzBenjamin** [comment]
Hey kisu,
sorry for the late reply. Could you share more of your code? Did you link the C# project to FlexCLI.dll properly by adding a reference?

**Comment by kisu2511** [comment]
@HeinzBenjamin 

Hello Benjamin
I tested your latest dlls in my test code again.
And also I think that I was properly coping all libs in the bin folder.

but in this stage, i saw another exception as shown below.

System.TypeInitializationException: 'The type initializer for '<Module>' threw an exception.'
EntryPointNotFoundException: A library name must be specified in a DllImport attribute applied to non-IJW methods.

I couldn't recognize which dll has the problem.
Can you share some test code using your dlls?

**Comment by HeinzBenjamin** [comment]
Hi kisu2511,
sorry for not responding. Did you figure it out last year?
